options:
  docker: true
pipelines:
  branches:
    master:
      - step:
          name: Sample RBAC
          deployment: production
          image: python:3.7.2
          services:
            - docker
          caches:
            - docker
          script:
            - pip3 install --no-cache-dir -q 'pipenv==2018.11.26' && pipenv install --deploy --system
            - pytest
            - docker-compose build
definitions:
  caches:
    bundler: /usr/local/bundle
